[package]
name = "knowit19-day01"
version = "0.1.0"
authors = ["Øyvind Ingvaldsen <oyvind.ingvaldsen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
